# Site settings
title: "Debut Island"
email: tnecivl@gmail.com
description: "A dark blog theme for Jekyll forked by Tneciv."
baseurl: ""
url: "http://tneciv.github.io/"
title_description: "O ever youthful, O ever weeping."
title_image: "http://i.imgur.com/ozCHF4m.jpg"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: http://tneciv.github.io/
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
github_username:  Tneciv
wechat: debut_
stackoverflow_link: http://tneciv.github.io/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by Jacob Tomlinson forked by <a href=\"https://twitter.com/_JacobTomlinson\">Tneciv</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/Tneciv\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
