# Site settings
title: "Debut Island"
email: tnecivl@gmail.com
description: "A dark blog theme for Jekyll forked by Tneciv."
baseurl: ""
url: "http://tneciv.github.io/"
title_description: "O ever youthful, O ever weeping."
title_image: "http://i.imgur.com/5tCDcyk.png"
google_analytics: "UA-66290738-1"
disqus_account: cartenoire
github_repository: http://tneciv.github.io/
addthis_id: ra-513c6fa83da6ec67
post_limit: 5
encoding: "utf-8"

# Social usernames/URLs
github_username:  Tneciv
weixin: debut_
stackoverflow_link: http://tneciv.github.io/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://github.com/Tneciv\">Tneciv</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/Tneciv\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

# Markdown Conversion
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
