# Site settings
title: "Debut Island"
email: tnecivl@gmail.com
description: "A dark blog theme for Jekyll forked by Tneciv."
baseurl: ""
url: "http://tneciv.github.io/"
title_description: ""Japhy," I said out loud, I don't know when we'll meet again or what'll happen in the future, but Desolation, Desolation, I owe so much to Desolation. Thank you for guiding me to the place I learned all. Now comes the sadness of coming back to cities and I've grown two months older and there's all that humanity of bars and burlesque shows and gritty love, all upsidedown in the void God bless them, but Japhy you and me forever know, O ever youthful, O ever weeping.""
title_image: "http://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: http://tneciv.github.io/
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
github_username:  Tneciv
linkedin_link: http://tneciv.github.io/
stackoverflow_link: http://tneciv.github.io/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by Jacob Tomlinson forked by <a href=\"https://twitter.com/_JacobTomlinson\">Tneciv</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/Tneciv\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
